### ISSUE TITLE
createOrder doesn't push order to this.orders until it is executed

### ISSUE THREAD

**Issue by StaRenn** [debut-js/Core#11]
I had this trouble with onTick, i has a condition that refers to this.orders.length

`if (tick.h > this.maShort1 && this.prevTick.h < this.maShort1 && this.orders.length < 1) {
    await this.createOrder(OrderType.SELL);
}`

it can create order on every tick, until the first order is executed, personally i had 7 orders instead of 1

**Comment by BusinessDuck** [comment]
This pr will fix it. Orders now synchronously added to orders list.
