### ISSUE TITLE
Infinite loop on await this.closeAll

### ISSUE THREAD

**Issue by StaRenn** [debut-js/Core#12]
i have this condition called on every tick, it crashes with heap out of memory, it might be caused by this issue  #https://github.com/debut-js/Core/issues/11
`if (
            (tick.c > this.maValue && this.prevTick.c < this.maValue) ||
            (tick.c < this.maValue && this.prevTick.c >  this.maValue)
        ) {
            console.log('Closing all orders');
            await this.closeAll();
        }
)`

**Comment by BusinessDuck** [comment]
The problem with while loop, we need to remove item before networking phase, because it can take a lot of time and non blocking other actions. That mean `this.closeAll()` may be called twice and get infite loop in while when all orders have `processing = true` flag
