### ISSUE TITLE
Fix linting

### ISSUE THREAD

**Issue by solarfrantz** [debut-js/Core#15]
I've clone your repo and wanted to create a PR on a branch in order to fix the linting, but I can't :(
Later on I want to add a new type of transport for [XTB](http://developers.xstore.pro/documentation/current).

Do I need to fork and only after make a PR into your repo ?

**Comment by BusinessDuck** [comment]
> I've clone your repo and wanted to create a PR on a branch in order to fix the linting, but I can't :( Later on I want to add a new type of transport for [XTB](http://developers.xstore.pro/documentation/current).
> 
> Do I need to fork and only after make a PR into your repo ?

You should fork me, than clone you own repo, then make a PR from you repo to my.
